### File Demand Elctic

In [212]:
import pandas as pd

file_path = r"C:\Users\ACER\Downloads\Electricity Consumption Forecasting in France 2012-2026\Electricity-Consumption-Forecasting-in-France-2012-2026-main\Data\Raw\Demand Elctic.csv"

# Đọc file với phân cách dấu chấm phẩy
df_1= pd.read_csv(file_path, sep=";")

# Kiểm tra schema và các dòng đầu tiên
print(df_1.info())
print(df_1.head())

<class 'pandas.DataFrame'>
RangeIndex: 508320 entries, 0 to 508319
Data columns (total 37 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Périmètre                                  508320 non-null  str
 1   Nature                                     508320 non-null  str
 2   Date                                       508320 non-null  str
 3   Heure                                      508320 non-null  str
 4   Date et Heure                              508320 non-null  str
 5   Consommation (MW)                          254160 non-null  float64
 6   Prévision J-1 (MW)                         508320 non-null  int64
 7   Prévision J (MW)                           508320 non-null  int64
 8   Fioul (MW)                                 254160 non-null  float64
 9   Charbon (MW)                               254160 non-null  float64
 10  Gaz (MW)                                   254160 non-null  float64
 11  Nucléaire (MW)                             254160 non-null  float64
 12  Eolien (MW)                                254160 non-null  float64
 13  Solaire (MW)                               254160 non-null  float64
 14  Hydraulique (MW)                           254160 non-null  float64
 15  Pompage (MW)                               254160 non-null  float64
 16  Bioénergies (MW)                           254160 non-null  float64
 17  Ech. physiques (MW)                        254160 non-null  float64
 18  Taux de CO2 (g/kWh)                        254160 non-null  float64
 19  Ech. comm. Angleterre (MW)                 288760 non-null  float64
 20  Ech. comm. Espagne (MW)                    289384 non-null  float64
 21  Ech. comm. Italie (MW)                     289374 non-null  float64
 22  Ech. comm. Suisse (MW)                     289384 non-null  float64
 23  Ech. comm. Allemagne-Belgique (MW)         289364 non-null  object
 24  Fioul - TAC (MW)                           236591 non-null  float64
 25  Fioul - Cogénération (MW)                  236591 non-null  float64
 26  Fioul - Autres (MW)                        236591 non-null  float64
 27  Gaz - TAC (MW)                             236591 non-null  float64
 28  Gaz - Cogénération (MW)                    254160 non-null  object
 29  Gaz - CCG (MW)                             236591 non-null  float64
 30  Gaz - Autres (MW)                          236591 non-null  float64
 31  Hydraulique - Fil de l'eau + éclusée (MW)  236591 non-null  float64
 32  Hydraulique - Lacs (MW)                    236591 non-null  float64
 33  Hydraulique - STEP turbinage (MW)          236591 non-null  float64
 34  Bioénergies - Déchets (MW)                 236591 non-null  float64
 35  Bioénergies - Biomasse (MW)                236591 non-null  float64
 36  Bioénergies - Biogaz (MW)                  236591 non-null  float64
dtypes: float64(28), int64(2), object(2), str(5)
memory usage: 143.5+ MB
None
  Périmètre               Nature        Date  Heure  \
0    France  Données consolidées  2026-06-30  23:45
1    France  Données consolidées  2026-06-30  23:30
2    France  Données consolidées  2026-06-30  23:15
3    France  Données consolidées  2026-06-30  23:00
4    France  Données consolidées  2026-06-30  22:45

               Date et Heure  Consommation (MW)  Prévision J-1 (MW)  \
0  2026-07-01T04:45:00+07:00                NaN               48050
1  2026-07-01T04:30:00+07:00            48906.0               49100
2  2026-07-01T04:15:00+07:00                NaN               49900
3  2026-07-01T04:00:00+07:00            49944.0               50700
4  2026-07-01T03:45:00+07:00                NaN               50000

   Prévision J (MW)  Fioul (MW)  Charbon (MW)  ...  Gaz - TAC (MW)  \
0             48200         NaN           NaN  ...             NaN
1             49400        51.0          14.0  ...            92.0
2             50300         NaN           NaN  ...             NaN
3             51200        51.0          14.0  ...            95.0
4             50550         NaN           NaN  ...             NaN

   Gaz - Cogénération (MW)  Gaz - CCG (MW)  Gaz - Autres (MW)  \
0                      NaN             NaN                NaN
1                    169.0          4744.0               46.0
2                      NaN             NaN                NaN
3                    178.0          4748.0               67.0
4                      NaN             NaN                NaN

   Hydraulique - Fil de l'eau + éclusée (MW)  Hydraulique - Lacs (MW)  \
0                                        NaN                      NaN
1                                     3658.0                   2910.0
2                                        NaN                      NaN
3                                     3697.0                   2999.0
4                                        NaN                      NaN

   Hydraulique - STEP turbinage (MW)  Bioénergies - Déchets (MW)  \
0                                NaN                         NaN
1                             2695.0                       406.0
2                                NaN                         NaN
3                             2918.0                       410.0
4                                NaN                         NaN

   Bioénergies - Biomasse (MW)  Bioénergies - Biogaz (MW)
0                          NaN                        NaN
1                        410.0                      297.0
2                          NaN                        NaN
3                        409.0                      300.0
4                          NaN                        NaN

[5 rows x 37 columns]

C:\Users\ACER\AppData\Local\Temp\ipykernel_29360\3137359548.py:6: DtypeWarning: Columns (23: Ech. comm. Allemagne-Belgique (MW), 28: Gaz - Cogénération (MW)) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1= pd.read_csv(file_path, sep=";")

In [213]:
df_1.columns

Index(['Périmètre', 'Nature', 'Date', 'Heure', 'Date et Heure',
       'Consommation (MW)', 'Prévision J-1 (MW)', 'Prévision J (MW)',
       'Fioul (MW)', 'Charbon (MW)', 'Gaz (MW)', 'Nucléaire (MW)',
       'Eolien (MW)', 'Solaire (MW)', 'Hydraulique (MW)', 'Pompage (MW)',
       'Bioénergies (MW)', 'Ech. physiques (MW)', 'Taux de CO2 (g/kWh)',
       'Ech. comm. Angleterre (MW)', 'Ech. comm. Espagne (MW)',
       'Ech. comm. Italie (MW)', 'Ech. comm. Suisse (MW)',
       'Ech. comm. Allemagne-Belgique (MW)', 'Fioul - TAC (MW)',
       'Fioul - Cogénération (MW)', 'Fioul - Autres (MW)', 'Gaz - TAC (MW)',
       'Gaz - Cogénération (MW)', 'Gaz - CCG (MW)', 'Gaz - Autres (MW)',
       'Hydraulique - Fil de l'eau + éclusée (MW)', 'Hydraulique - Lacs (MW)',
       'Hydraulique - STEP turbinage (MW)', 'Bioénergies - Déchets (MW)',
       'Bioénergies - Biomasse (MW)', 'Bioénergies - Biogaz (MW)'],
      dtype='str')

In [214]:
df_1 = df_1.rename(columns={
    "Périmètre": "Phạm vi",
    "Nature": "Loại dữ liệu",
    "Date": "Ngày",
    "Heure": "Giờ",
    "Date et Heure": "Ngày giờ",
    "Consommation (MW)": "Tiêu thụ điện theo nửa giờ (MW)",
    "Prévision J-1 (MW)": "Dự báo ngày trước (MW)",
    "Prévision J (MW)": "Dự báo trong ngày (MW)",
    "Fioul (MW)": "Điện dầu (MW)",
    "Charbon (MW)": "Điện than (MW)",
    "Gaz (MW)": "Điện khí (MW)",
    "Nucléaire (MW)": "Điện hạt nhân (MW)",
    "Eolien (MW)": "Điện gió (MW)",
    "Solaire (MW)": "Điện mặt trời (MW)",
    "Hydraulique (MW)": "Điện thủy điện (MW)",
    "Pompage (MW)": "Điện bơm tích năng (MW)",
    "Bioénergies (MW)": "Điện sinh khối và năng lượng sinh học (MW)",
    "Ech. physiques (MW)": "Trao đổi điện vật lý (MW)",
    "Taux de CO2 (g/kWh)": "Cường độ phát thải CO2 (g/kWh)",
    "Ech. comm. Angleterre (MW)": "Trao đổi điện thương mại với Anh (MW)",
    "Ech. comm. Espagne (MW)": "Trao đổi điện thương mại với Tây Ban Nha (MW)",
    "Ech. comm. Italie (MW)": "Trao đổi điện thương mại với Ý (MW)",
    "Ech. comm. Suisse (MW)": "Trao đổi điện thương mại với Thụy Sĩ (MW)",
    "Ech. comm. Allemagne-Belgique (MW)": "Trao đổi điện thương mại với Đức-Bỉ (MW)",
    "Fioul - TAC (MW)": "Điện dầu tuabin khí (MW)",
    "Fioul - Cogénération (MW)": "Điện dầu đồng phát (MW)",
    "Fioul - Autres (MW)": "Điện dầu loại khác (MW)",
    "Gaz - TAC (MW)": "Điện khí tuabin khí (MW)",
    "Gaz - Cogénération (MW)": "Điện khí đồng phát (MW)",
    "Gaz - CCG (MW)": "Điện khí chu trình hỗn hợp (MW)",
    "Gaz - Autres (MW)": "Điện khí loại khác (MW)",
    "Hydraulique - Fil de l'eau + éclusée (MW)": "Thủy điện dòng chảy và điều tiết theo đợt (MW)",
    "Hydraulique - Lacs (MW)": "Thủy điện hồ chứa (MW)",
    "Hydraulique - STEP turbinage (MW)": "Thủy điện tích năng khi phát điện (MW)",
    "Bioénergies - Déchets (MW)": "Điện từ chất thải (MW)",
    "Bioénergies - Biomasse (MW)": "Điện sinh khối (MW)",
    "Bioénergies - Biogaz (MW)": "Điện khí sinh học (MW)"
})

In [215]:
df_1 = df_1[[
    "Phạm vi",
    "Ngày",
    "Giờ",
    "Ngày giờ",
    "Tiêu thụ điện theo nửa giờ (MW)"
]]

In [216]:
df_1.isna().sum()

Phạm vi                                 0
Ngày                                    0
Giờ                                     0
Ngày giờ                                0
Tiêu thụ điện theo nửa giờ (MW)    254160
dtype: int64

In [217]:
print(df_1[df_1["Tiêu thụ điện theo nửa giờ (MW)"].isna()]["Giờ"].value_counts().sort_index())

Giờ
00:15    5295
00:45    5295
01:15    5295
01:45    5295
02:15    5295
02:45    5295
03:15    5295
03:45    5295
04:15    5295
04:45    5295
05:15    5295
05:45    5295
06:15    5295
06:45    5295
07:15    5295
07:45    5295
08:15    5295
08:45    5295
09:15    5295
09:45    5295
10:15    5295
10:45    5295
11:15    5295
11:45    5295
12:15    5295
12:45    5295
13:15    5295
13:45    5295
14:15    5295
14:45    5295
15:15    5295
15:45    5295
16:15    5295
16:45    5295
17:15    5295
17:45    5295
18:15    5295
18:45    5295
19:15    5295
19:45    5295
20:15    5295
20:45    5295
21:15    5295
21:45    5295
22:15    5295
22:45    5295
23:15    5295
23:45    5295
Name: count, dtype: int64

In [218]:
# Xóa các dòng bị thiếu tiêu thụ điện(Do là 15p)
df_1 = df_1.dropna(subset=["Tiêu thụ điện theo nửa giờ (MW)"])

In [219]:
# Chuyển cột ngày và công suất sang đúng kiểu dữ liệu
df_1["Ngày"] = pd.to_datetime(df_1["Ngày"])
df_1["Tiêu thụ điện theo nửa giờ (MW)"] = pd.to_numeric(
    df_1["Tiêu thụ điện theo nửa giờ (MW)"], errors="coerce")

In [220]:
daily = df_1.groupby("Ngày").size().reset_index(name="Số_lần_đo")
print(daily)

           Ngày  Số_lần_đo
0    2012-01-01         48
1    2012-01-02         48
2    2012-01-03         48
3    2012-01-04         48
4    2012-01-05         48
...         ...        ...
5290 2026-06-26         48
5291 2026-06-27         48
5292 2026-06-28         48
5293 2026-06-29         48
5294 2026-06-30         48

[5295 rows x 2 columns]

In [221]:
daily = df_1.groupby("Ngày")["Tiêu thụ điện theo nửa giờ (MW)"].sum().reset_index()
daily["Tổng tiêu thụ điện (MWh)"] = daily["Tiêu thụ điện theo nửa giờ (MW)"] / 2
daily = daily.drop(columns=["Tiêu thụ điện theo nửa giờ (MW)"])

print(daily)

           Ngày  Tổng tiêu thụ điện (MWh)
0    2012-01-01                 1235796.0
1    2012-01-02                 1456407.5
2    2012-01-03                 1626290.5
3    2012-01-04                 1632701.5
4    2012-01-05                 1659777.5
...         ...                       ...
5290 2026-06-26                 1252500.0
5291 2026-06-27                 1125367.0
5292 2026-06-28                 1045380.0
5293 2026-06-29                 1143263.5
5294 2026-06-30                 1158901.5

[5295 rows x 2 columns]

In [222]:
daily["Ngày"] = pd.to_datetime(daily["Ngày"])
daily = daily[
    (daily["Ngày"] >= "2012-01-01") &
    (daily["Ngày"] <= "2026-05-25")
].reset_index(drop=True)

daily.index = daily.index + 1

In [223]:
df_1 = daily.copy()

In [224]:
print(df_1.tail())

           Ngày  Tổng tiêu thụ điện (MWh)
5255 2026-05-21                 1091310.5
5256 2026-05-22                 1074661.0
5257 2026-05-23                  964604.5
5258 2026-05-24                  915477.5
5259 2026-05-25                  970611.0

### File weather_daily_paris

In [225]:
import pandas as pd
from pathlib import Path

file_path = Path(r"C:\Users\ACER\Downloads\Electricity Consumption Forecasting in France 2012-2026\Electricity-Consumption-Forecasting-in-France-2012-2026-main\Data\Raw\weather_daily_paris.csv")

df_2 = pd.read_csv(file_path)
print(df_2.head())

         date  temperature_mean  temperature_max  humidity_mean  \
0  2012-01-01         12.137500             12.9      92.291667
1  2012-01-02          8.470833             11.5      84.958333
2  2012-01-03          8.600000             12.6      83.666667
3  2012-01-04          7.745833              9.2      75.583333
4  2012-01-05          9.395833             10.9      74.708333

   cloud_cover_mean  shortwave_radiation_mean  wind_speed_mean  \
0         99.958333                  6.333333        23.212500
1         70.416667                 39.416667        18.487500
2         91.083333                 11.750000        28.704167
3         72.375000                 50.208333        22.066667
4         77.208333                 17.666667        34.062500

   precipitation_sum  valid_hour_count
0                0.6                24
1                8.9                24
2                8.8                24
3                0.1                24
4                3.2                24

In [226]:
df_2.head()

,date,temperature_mean,temperature_max,humidity_mean,cloud_cover_mean,shortwave_radiation_mean,wind_speed_mean,precipitation_sum,valid_hour_count
0,2012-01-01,12.137500,12.9,92.291667,99.958333,6.333333,23.212500,0.6,24
1,2012-01-02,8.470833,11.5,84.958333,70.416667,39.416667,18.487500,8.9,24
2,2012-01-03,8.600000,12.6,83.666667,91.083333,11.750000,28.704167,8.8,24
3,2012-01-04,7.745833,9.2,75.583333,72.375000,50.208333,22.066667,0.1,24
4,2012-01-05,9.395833,10.9,74.708333,77.208333,17.666667,34.062500,3.2,24

In [227]:
df_2.columns

Index(['date', 'temperature_mean', 'temperature_max', 'humidity_mean',
       'cloud_cover_mean', 'shortwave_radiation_mean', 'wind_speed_mean',
       'precipitation_sum', 'valid_hour_count'],
      dtype='str')

In [228]:
df_2 = df_2.rename(columns={
    'date': 'Ngày',
    'temperature_mean': 'Nhiệt_độ',
    'temperature_max': 'Nhiệt_độ_cao_nhất',
    'humidity_mean': 'Độ_ẩm',
    'cloud_cover_mean': 'Độ_che_phủ_mây',
    'shortwave_radiation_mean': 'Bức_xạ_sóng_ngắn',
    'wind_speed_mean': 'Tốc_độ_gió',
    'precipitation_sum': 'Tổng_lượng_mưa',
    'valid_hour_count': 'Số_giờ_hợp_lệ'
})

In [229]:
df_2 = df_2.drop(columns=["Nhiệt_độ_cao_nhất"])

In [230]:
print(df_2.columns)

Index(['Ngày', 'Nhiệt_độ', 'Độ_ẩm', 'Độ_che_phủ_mây', 'Bức_xạ_sóng_ngắn',
       'Tốc_độ_gió', 'Tổng_lượng_mưa', 'Số_giờ_hợp_lệ'],
      dtype='str')

In [231]:
df_2['Ngày'] = pd.to_datetime(df_2['Ngày'])

start_date = df_2['Ngày'].min().strftime('%Y-%m-%d')
end_date = df_2['Ngày'].max().strftime('%Y-%m-%d')

In [232]:
print(f"Ngày bắt đầu: {start_date}")
print(f"Ngày kết thúc: {end_date}")

Ngày bắt đầu: 2012-01-01
Ngày kết thúc: 2026-06-30

In [233]:
df_2 = df_2[
    (df_2["Ngày"] >= "2012-01-01") &
    (df_2["Ngày"] <= "2026-05-25")
].reset_index(drop=True)

In [234]:
df_2.tail(5)

,Ngày,Nhiệt_độ,Độ_ẩm,Độ_che_phủ_mây,Bức_xạ_sóng_ngắn,Tốc_độ_gió,Tổng_lượng_mưa,Số_giờ_hợp_lệ
5254,2026-05-21,17.537500,73.250000,37.666667,298.000000,4.233333,0.0,24
5255,2026-05-22,20.516667,68.000000,14.000000,329.666667,4.729167,0.0,24
5256,2026-05-23,22.587500,63.875000,23.250000,328.916667,3.462500,0.0,24
5257,2026-05-24,24.112500,64.833333,8.958333,329.458333,6.750000,0.0,24
5258,2026-05-25,25.475000,61.000000,24.666667,327.916667,8.675000,0.0,24

### File french_holidays.csv

In [235]:
import pandas as pd
from pathlib import Path

file_path = Path(r"C:\Users\ACER\Downloads\Electricity Consumption Forecasting in France 2012-2026\Electricity-Consumption-Forecasting-in-France-2012-2026-main\Data\Raw\french_holidays.csv")

df_3 = pd.read_csv(file_path)
print(df_3.head())

         date     holiday_name  is_holiday
0  2012-01-01      1er janvier           1
1  2012-04-09  Lundi de Pâques           1
2  2012-05-01          1er mai           1
3  2012-05-08            8 mai           1
4  2012-05-17        Ascension           1

In [236]:
df_3.columns

Index(['date', 'holiday_name', 'is_holiday'], dtype='str')

In [237]:
if 'holiday_name' in df_3.columns:
    df_3 = df_3.drop(columns=['holiday_name'])

In [238]:
df_3 = df_3.rename(columns={
    'date': 'Ngày',
    'is_holiday': 'Ngày_lễ'
})

In [239]:
df_3.head()

         Ngày  Ngày_lễ
0  2012-01-01        1
1  2012-04-09        1
2  2012-05-01        1
3  2012-05-08        1
4  2012-05-17        1

In [240]:
df_3['Ngày'] = pd.to_datetime(df_3['Ngày'])

start_date = df_3['Ngày'].min().strftime('%Y-%m-%d')
end_date = df_3['Ngày'].max().strftime('%Y-%m-%d')

In [241]:
print(f"Ngày bắt đầu: {start_date}")
print(f"Ngày kết thúc: {end_date}")

Ngày bắt đầu: 2012-01-01
Ngày kết thúc: 2026-05-25

In [242]:
full_calendar = pd.DataFrame({
    'Ngày': pd.date_range(start=start_date, end=end_date, freq='D')
})

In [243]:
full_calendar['Ngày'] = pd.to_datetime(full_calendar['Ngày'])
df_3['Ngày'] = pd.to_datetime(df_3['Ngày'])

In [244]:
df_3 = pd.merge(full_calendar, df_3, on='Ngày', how='left')

In [245]:
df_3['Ngày_lễ'] = df_3['Ngày_lễ'].fillna(0).astype(int)

In [246]:
df_3.tail()

           Ngày  Ngày_lễ
5254 2026-05-21        0
5255 2026-05-22        0
5256 2026-05-23        0
5257 2026-05-24        0
5258 2026-05-25        1

### Gộp File

In [247]:
for df in [df_1, df_2, df_3]:
    df["Ngày"] = pd.to_datetime(df["Ngày"])
    df.drop(df[
        (df["Ngày"] < "2012-01-01") |
        (df["Ngày"] > "2026-05-25")
    ].index, inplace=True)

merged = df_1.merge(df_2, on="Ngày", how="inner")
merged = merged.merge(df_3, on="Ngày", how="inner")

merged = merged.sort_values("Ngày").reset_index(drop=True)

print(merged)
print("Số dòng:", len(merged))

           Ngày  Tổng tiêu thụ điện (MWh)   Nhiệt_độ      Độ_ẩm  \
0    2012-01-01                 1235796.0  12.137500  92.291667
1    2012-01-02                 1456407.5   8.470833  84.958333
2    2012-01-03                 1626290.5   8.600000  83.666667
3    2012-01-04                 1632701.5   7.745833  75.583333
4    2012-01-05                 1659777.5   9.395833  74.708333
...         ...                       ...        ...        ...
5254 2026-05-21                 1091310.5  17.537500  73.250000
5255 2026-05-22                 1074661.0  20.516667  68.000000
5256 2026-05-23                  964604.5  22.587500  63.875000
5257 2026-05-24                  915477.5  24.112500  64.833333
5258 2026-05-25                  970611.0  25.475000  61.000000

      Độ_che_phủ_mây  Bức_xạ_sóng_ngắn  Tốc_độ_gió  Tổng_lượng_mưa  \
0          99.958333          6.333333   23.212500             0.6
1          70.416667         39.416667   18.487500             8.9
2          91.083333         11.750000   28.704167             8.8
3          72.375000         50.208333   22.066667             0.1
4          77.208333         17.666667   34.062500             3.2
...              ...               ...         ...             ...
5254       37.666667        298.000000    4.233333             0.0
5255       14.000000        329.666667    4.729167             0.0
5256       23.250000        328.916667    3.462500             0.0
5257        8.958333        329.458333    6.750000             0.0
5258       24.666667        327.916667    8.675000             0.0

      Số_giờ_hợp_lệ  Ngày_lễ
0                24        1
1                24        0
2                24        0
3                24        0
4                24        0
...             ...      ...
5254             24        0
5255             24        0
5256             24        0
5257             24        0
5258             24        1

[5259 rows x 10 columns]
Số dòng: 5259

In [248]:
from pathlib import Path

output_path = Path(r"C:\Users\ACER\Downloads\Electricity Consumption Forecasting in France 2012-2026\Electricity-Consumption-Forecasting-in-France-2012-2026-main\Data\Raw")
output_path.mkdir(parents=True, exist_ok=True)

merged.to_csv(output_path / "raw.csv", index=False, encoding="utf-8-sig")